server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_boot?serverTimezone=GMT%2B8
    username: root
    password: 1021
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false
    enabled: false
  redis:
    host: 10.3.52.172
    password:                 # Redis服务器连接密码（默认为空）
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

